#!/usr/bin/env python3
"""Rasterize ChicagoFLF into small uncompressed 1-bit UI fonts (Pillow/fonttools).
The UI uses three sizes with the same line metrics as CrossInk's original UI.
Source attribution is in assets/system6/README.md. No Apple system font required.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
from fontTools.ttLib import TTFont
ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'assets/system6/ChicagoFLF.ttf'
DEST = ROOT / 'src/components/themes/system6/System6FontData.h'
cmap = TTFont(SOURCE).getBestCmap()
codepoints = sorted(cp for cp in cmap if 32 <= cp < 256 or 0x2000 <= cp <= 0x206f or 0x2190 <= cp <= 0x2194)
parts = ['// Generated by scripts/generate_system6_font.py; do not edit.\n#pragma once\n#include <EpdFontData.h>\n']
for name, px, line, asc, desc in [('small', 16, 20, 17, -5), ('body', 20, 25, 21, -6), ('large', 24, 30, 25, -7)]:
    font = ImageFont.truetype(str(SOURCE), px)
    bitmap, glyphs, intervals = [], [], []
    for idx, cp in enumerate(codepoints):
        ch = chr(cp)
        x0,y0,x1,y1 = font.getbbox(ch, anchor='ls')
        width,height = x1-x0,y1-y0
        im = Image.new('1', (max(width,1), max(height,1)), 0)
        ImageDraw.Draw(im).text((-x0,-y0), ch, font=font, fill=1, anchor='ls', stroke_width=0)
        bits = [int(im.getpixel((x,y)) != 0) for y in range(height) for x in range(width)]
        bits += [0] * (-len(bits) % 8)
        data = [sum(bits[i+j] << (7-j) for j in range(8)) for i in range(0,len(bits),8)]
        advance = max(1, round(font.getlength(ch))) * 16
        glyphs.append((width,height,advance,x0,-y0,len(data),len(bitmap)))
        bitmap.extend(data)
        if intervals and cp == intervals[-1][1]+1: intervals[-1][1] = cp
        else: intervals.append([cp,cp,idx])
    prefix = 'system6_'+name
    parts.append('static constexpr uint8_t '+prefix+'Bitmap[] = {\n'+','.join(map(str,bitmap))+'\n};\n')
    parts.append('static constexpr EpdGlyph '+prefix+'Glyphs[] = {\n'+''.join('  {'+','.join(map(str,g))+'},\n' for g in glyphs)+'};\n')
    parts.append('static constexpr EpdUnicodeInterval '+prefix+'Intervals[] = {\n'+''.join('  {'+','.join(map(str,g))+'},\n' for g in intervals)+'};\n')
    parts.append(f'''static constexpr EpdFontData {prefix} = {{
  .bitmap = {prefix}Bitmap, .glyph = {prefix}Glyphs, .intervals = {prefix}Intervals,
  .intervalCount = {len(intervals)}, .advanceY = {line}, .ascender = {asc}, .descender = {desc}, .is2Bit = false
}};
''')
    print(f'{name}: {len(glyphs)} glyphs, {len(bitmap)} bitmap bytes')
DEST.write_text('\n'.join(parts))
